### ISSUE TITLE
dash==0.21.2 raise KeyError: 'index'

### ISSUE THREAD

**Issue by chuchuhao** [plotly/dash-auth#43]
follow the example code, following error raised 

``` 
$ python app.py
Traceback (most recent call last):
  File "app.py", line 49, in <module>
    APP_URL
  File "/home/tony/pi/lib/python3.6/site-packages/dash_auth/plotly_auth.py", line 17, in __init__
    Auth.__init__(self, app)
  File "/home/tony/pi/lib/python3.6/site-packages/dash_auth/auth.py", line 12, in __init__
    self._overwrite_index()
  File "/home/tony/pi/lib/python3.6/site-packages/dash_auth/auth.py", line 16, in _overwrite_index
    original_index = self.app.server.view_functions['index']
KeyError: 'index'
```

**Comment by chuchuhao** [comment]
found that I used the wrong version when following the example (0.4.0)
after update to 1.0.0 problem solved
