### ISSUE TITLE
BasicAuth - 'TypeError: ‘type’ object is not subscriptable '.

### ISSUE THREAD

**Issue by jdoe68877** [plotly/dash-auth#48]
I have incorporated an authentication functionality into my code based off of the official Dash-Auth docs. This app is to be hosted on heroku. Couple of things happen (Code is below) :

```
app = dash.Dash('app',server=server)
app = dash.Dash('auth')
auth = dash_auth.BasicAuth(
    app,
    (('abcde','1234',),)
)
```
Locally, the authentication works flawlessly, except that once you login into the app it saves the login info as cookies. Hence, if you would refresh the page or probably paste the link to a new window it wont ask for the login info again unless and until you clear you cookies in the browser.

Once the app is pushed to the heroku master it successfully deploys it, unfortunalely the app does not open due to an application error. On checking the heroku logs the error shown is below. This error is not shown if hosted locally.

> 'TypeError: ‘type’ object is not subscriptable '.

As per the [post](https://community.plot.ly/t/dash-authentication-issue/9990) I have removed dash.ly so im sure the error has nothing to do with it. As per this [post](https://community.plot.ly/t/enabling-authentication/4714/7) around the 8th comment someone raises the issue of the login but the reply is not definitive.

**Comment by chriddyp** [comment]
> Locally, the authentication works flawlessly, except that once you login into the app it saves the login info as cookies.

It does not actually. Basic auth is HTTP Authentication, here's how this works: http://qnimate.com/understanding-http-authentication-in-depth/. To log users out, the server must respond with a `401` status code, which you could wire in to your Dash app with a flask route.

I'm not sure about the heroku issue, I've deployed successfully before. It's also hard to say without a larger traceback of the "TypeError" issue

**Comment by mokshaxkrodha** [comment]
Below is the logs when I try to run the app:

```
2018-07-12T09:13:10.468466+00:00 app[web.1]: self.reap_workers()
2018-07-12T09:13:10.468511+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
2018-07-12T09:13:10.468876+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2018-07-12T09:13:10.468941+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2018-07-12T09:13:10.468966+00:00 app[web.1]:
2018-07-12T09:13:10.468968+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-07-12T09:13:10.468970+00:00 app[web.1]:
2018-07-12T09:13:10.468999+00:00 app[web.1]: Traceback (most recent call last):
2018-07-12T09:13:10.469031+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2018-07-12T09:13:10.469188+00:00 app[web.1]: sys.exit(run())
2018-07-12T09:13:10.469225+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2018-07-12T09:13:10.469421+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2018-07-12T09:13:10.469450+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 203, in run
2018-07-12T09:13:10.469674+00:00 app[web.1]: super(Application, self).run()
2018-07-12T09:13:10.469711+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
2018-07-12T09:13:10.469901+00:00 app[web.1]: Arbiter(self).run()
2018-07-12T09:13:10.469938+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 231, in run
2018-07-12T09:13:10.470189+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2018-07-12T09:13:10.470222+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 344, in halt
2018-07-12T09:13:10.470506+00:00 app[web.1]: self.stop()
2018-07-12T09:13:10.470543+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
2018-07-12T09:13:10.470874+00:00 app[web.1]: time.sleep(0.1)
2018-07-12T09:13:10.470904+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
2018-07-12T09:13:10.471135+00:00 app[web.1]: self.reap_workers()
2018-07-12T09:13:10.471173+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
2018-07-12T09:13:10.471543+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2018-07-12T09:13:10.471594+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2018-07-12T09:13:10.587074+00:00 heroku[web.1]: Process exited with status 1
2018-07-12T09:13:10.605756+00:00 heroku[web.1]: State changed from up to crashed
2018-07-12T09:13:10.608137+00:00 heroku[web.1]: State changed from crashed to starting
2018-07-12T09:13:10.000000+00:00 app[api]: Build succeeded
2018-07-12T09:13:18.006071+00:00 heroku[web.1]: Starting process with command `gunicorn app:server --workers 2`
2018-07-12T09:13:20.581987+00:00 app[web.1]: [2018-07-12 09:13:20 +0000] [4] [INFO] Starting gunicorn 19.7.1
2018-07-12T09:13:20.582569+00:00 app[web.1]: [2018-07-12 09:13:20 +0000] [4] [INFO] Listening at: http://0.0.0.0:31209 (4)
2018-07-12T09:13:20.582687+00:00 app[web.1]: [2018-07-12 09:13:20 +0000] [4] [INFO] Using worker: sync
2018-07-12T09:13:20.586407+00:00 app[web.1]: [2018-07-12 09:13:20 +0000] [8] [INFO] Booting worker with pid: 8
2018-07-12T09:13:20.682936+00:00 app[web.1]: [2018-07-12 09:13:20 +0000] [9] [INFO] Booting worker with pid: 9
2018-07-12T09:13:21.744776+00:00 heroku[web.1]: State changed from starting to up
2018-07-12T09:13:24.088049+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning:
2018-07-12T09:13:24.088093+00:00 app[web.1]:
2018-07-12T09:13:24.088105+00:00 app[web.1]: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2018-07-12T09:13:24.088107+00:00 app[web.1]:
2018-07-12T09:13:24.093288+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning:
2018-07-12T09:13:24.093291+00:00 app[web.1]:
2018-07-12T09:13:24.093294+00:00 app[web.1]: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2018-07-12T09:13:24.093295+00:00 app[web.1]:
2018-07-12T09:13:24.105325+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [8] [ERROR] Exception in worker process
2018-07-12T09:13:24.105329+00:00 app[web.1]: Traceback (most recent call last):
2018-07-12T09:13:24.105331+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-07-12T09:13:24.105333+00:00 app[web.1]: worker.init_process()
2018-07-12T09:13:24.105335+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-07-12T09:13:24.105336+00:00 app[web.1]: self.load_wsgi()
2018-07-12T09:13:24.105338+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-07-12T09:13:24.105339+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-12T09:13:24.105341+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-12T09:13:24.105343+00:00 app[web.1]: self.callable = self.load()
2018-07-12T09:13:24.105345+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-12T09:13:24.105346+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-12T09:13:24.105348+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-12T09:13:24.105350+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-12T09:13:24.105351+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-07-12T09:13:24.105353+00:00 app[web.1]: __import__(module)
2018-07-12T09:13:24.105354+00:00 app[web.1]: File "/app/app.py", line 15, in <module>
2018-07-12T09:13:24.105356+00:00 app[web.1]: (('abcd','1234',),)
2018-07-12T09:13:24.105357+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/dash_auth/basic_auth.py", line 8, in __init__
2018-07-12T09:13:24.105359+00:00 app[web.1]: Auth.__init__(self, app)
2018-07-12T09:13:24.105360+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/dash_auth/auth.py", line 10, in __init__
2018-07-12T09:13:24.105362+00:00 app[web.1]: self._index_view_name = app.config['routes_pathname_prefix']
2018-07-12T09:13:24.105363+00:00 app[web.1]: TypeError: 'type' object is not subscriptable
2018-07-12T09:13:24.107125+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [9] [ERROR] Exception in worker process
2018-07-12T09:13:24.107128+00:00 app[web.1]: Traceback (most recent call last):
2018-07-12T09:13:24.107130+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-07-12T09:13:24.107132+00:00 app[web.1]: worker.init_process()
2018-07-12T09:13:24.107133+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-07-12T09:13:24.107135+00:00 app[web.1]: self.load_wsgi()
2018-07-12T09:13:24.107136+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-07-12T09:13:24.107138+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-12T09:13:24.107140+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-12T09:13:24.107141+00:00 app[web.1]: self.callable = self.load()
2018-07-12T09:13:24.107143+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-12T09:13:24.107145+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-12T09:13:24.107146+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-12T09:13:24.107148+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-12T09:13:24.107149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-07-12T09:13:24.107151+00:00 app[web.1]: __import__(module)
2018-07-12T09:13:24.107152+00:00 app[web.1]: File "/app/app.py", line 15, in <module>
2018-07-12T09:13:24.107153+00:00 app[web.1]: (('abcd','1234',),)
2018-07-12T09:13:24.107155+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/dash_auth/basic_auth.py", line 8, in __init__
2018-07-12T09:13:24.107157+00:00 app[web.1]: Auth.__init__(self, app)
2018-07-12T09:13:24.107158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/dash_auth/auth.py", line 10, in __init__
2018-07-12T09:13:24.107160+00:00 app[web.1]: self._index_view_name = app.config['routes_pathname_prefix']
2018-07-12T09:13:24.107167+00:00 app[web.1]: TypeError: 'type' object is not subscriptable
2018-07-12T09:13:24.109122+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-07-12T09:13:24.110934+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [9] [INFO] Worker exiting (pid: 9)
2018-07-12T09:13:24.322376+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [4] [INFO] Shutting down: Master
2018-07-12T09:13:24.322566+00:00 app[web.1]: [2018-07-12 09:13:24 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-07-12T09:13:24.224229+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=reactgfkdxb.herokuapp.com request_id=f905191a-ed79-419e-b618-5827e01eb957 fwd="94.200.109.116" dyno=web.1 connect=1ms service=1604ms status=503 bytes=0 protocol=https
2018-07-12T09:13:24.421709+00:00 heroku[web.1]: State changed from up to crashed
2018-07-12T09:13:24.399090+00:00 heroku[web.1]: Process exited with status 3
2018-07-12T09:13:25.630976+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=reactgfkdxb.herokuapp.com request_id=ac0a7b8a-3c89-4de4-8bac-00af2795c7af fwd="94.200.109.116" dyno= connect= service= status=503 bytes= protocol=https
```
